default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     50
  username: postgres
  password: postgres

development:
  <<: *default
  database: gv_talent_development
